SELECT * FROM tasks WHERE status_id = (SELECT id FROM status WHERE name = 'new');


-- id|title                                            |description                                                                                                                                                                                            |status_id|user_id|
-- --+-------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-------+
--  1|Together herself hotel word may leader should.   |Television they vote adult teach. Include life crime.¶Interesting have include Mr. Run program reality dark manager blood way along.¶Goal miss decide wall smile enjoy it. Talk interesting shake.     |        1|     10|
--  3|Within young near huge help happy.               |Sometimes second scientist production rest friend. Read door out will. Five even important house energy.¶Threat social ago ground important lose.¶Business build look. Off stay east we including this.|        1|      6|
--  4|State than decide modern real add.               |Buy tonight couple born. Must certain but. Agency usually option buy property fall success.                                                                                                            |        1|     10|
--  5|Money toward image him ball gun.                 |The must PM then owner none number. Food expect with position.¶Stand land accept course include generation in yet. Truth probably just thing degree inside scientist some.                             |        1|      1|
--  6|Different law expert. Think someone street above.|Blood reflect old success. Our pull site.¶Inside their threat glass. There either team. Level power growth difficult cost general.                                                                     |        1|      7|
--  7|Police cause participant.                        |Especially every sort relationship me inside. Thing government eight. Now state wind trouble hit then four.¶Speech off always authority.                                                               |        1|     10|
--  9|Radio side wish guy hit memory.                  |Organization window military development day. Them such protect kitchen employee film answer. Yeah natural its.                                                                                        |        1|      3|
-- 13|My radio section enjoy technology.               |Positive fish decade mission. Easy study paper. Show especially week mind could.                                                                                                                       |        1|      7|
-- 16|Reduce American whom bring marriage.             |Major another study research. Hour health road last.¶Budget bad point consider. Agreement value will discussion course site want. Evidence hope team executive side southern hair.                     |        1|      7|
-- 18|True cause once wall authority impact.           |Ability that side mention well his. Present less especially drop season general bed.¶Difficult western old media. However response administration letter challenge participant. Radio focus each.      |        1|      1|
-- 20|Let spring also reveal every. Present get put.   |Often might us organization coach world than. Newspaper least traditional case. Discover stand chair hospital head.                                                                                    |        1|      8|
