UPDATE tasks SET description = '' WHERE id = 4;
UPDATE tasks SET description = NULL WHERE id = 6;


-- id|title                                            |description                                                                                                                                                                                            |status_id|user_id|
-- --+-------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-------+
--  1|Together herself hotel word may leader should.   |Television they vote adult teach. Include life crime.¶Interesting have include Mr. Run program reality dark manager blood way along.¶Goal miss decide wall smile enjoy it. Talk interesting shake.     |        1|     10|
--  3|Within young near huge help happy.               |Sometimes second scientist production rest friend. Read door out will. Five even important house energy.¶Threat social ago ground important lose.¶Business build look. Off stay east we including this.|        1|      6|
--  5|Money toward image him ball gun.                 |The must PM then owner none number. Food expect with position.¶Stand land accept course include generation in yet. Truth probably just thing degree inside scientist some.                             |        1|      1|
--  8|Range great detail always.                       |Yeah become computer. Value think performance drive name. Especially toward agree walk moment firm American many.                                                                                      |        2|      7|
--  9|Radio side wish guy hit memory.                  |Organization window military development day. Them such protect kitchen employee film answer. Yeah natural its.                                                                                        |        1|      3|
-- 11|Ready affect whatever develop discover.          |Capital security quickly perhaps stand wife. Follow attorney form seven. Discover rock when.¶Despite mention else bar talk. Admit manage test which gun. Head follow have seem.                        |        3|      1|
-- 13|My radio section enjoy technology.               |Positive fish decade mission. Easy study paper. Show especially week mind could.                                                                                                                       |        1|      7|
-- 14|Must score area real alone growth plan claim.    |Bed difficult front voice. Statement can Congress painting sit.¶Vote wall it. Happen social glass small keep but keep cost.                                                                            |        2|      7|
-- 15|Hold game per threat avoid color wait.           |Identify there group thing school whose station. Assume college little offer stock before down.                                                                                                        |        3|      2|
-- 16|Reduce American whom bring marriage.             |Major another study research. Hour health road last.¶Budget bad point consider. Agreement value will discussion course site want. Evidence hope team executive side southern hair.                     |        1|      7|
-- 18|True cause once wall authority impact.           |Ability that side mention well his. Present less especially drop season general bed.¶Difficult western old media. However response administration letter challenge participant. Radio focus each.      |        1|      1|
-- 20|Let spring also reveal every. Present get put.   |Often might us organization coach world than. Newspaper least traditional case. Discover stand chair hospital head.                                                                                    |        1|      8|
--  7|Police cause participant.                        |Especially every sort relationship me inside. Thing government eight. Now state wind trouble hit then four.¶Speech off always authority.                                                               |        3|     10|
-- 10|Difficult almost foreign hit carry past first.   |Site long whatever. Peace enough effort. Finish rather wind watch ready.¶Particular four side address reflect degree enjoy.                                                                            |        3|     10|
-- 21|Wash the dish                                    |Take it, wash it, dry it                                                                                                                                                                               |        2|      4|
--  4|State than decide modern real add.               |                                                                                                                                                                                                       |        1|     10|
--  6|Different law expert. Think someone street above.|                                                                                                                                                                                                       |        1|      7|